/**
 * @typedef {Object} DocumentTypeInfo
 * @property {DocumentType} documentType - 帳票種別
 * @property {DepartmentNameType} departmentName - 所轄部署
 */

/**
 *  @type {DocumentTypeInfo[]} 帳票種別一覧
 */
export const DOCUMENT_TYPE_LIST = [
  { documentType: 'C301', departmentName: '事務企画推進部' },
  { documentType: 'C302', departmentName: '事務企画推進部' },
  { documentType: 'C303', departmentName: '事務企画推進部' },
  { documentType: 'C304', departmentName: '事務企画推進部' },
  { documentType: 'C305', departmentName: '事務企画推進部' },
  { documentType: 'C306', departmentName: '事務企画推進部' },
  { documentType: 'C307', departmentName: '事務企画推進部' },
  { documentType: 'C308', departmentName: '事務企画推進部' },
  { documentType: 'C010201', departmentName: '事務企画推進部' },
  { documentType: 'C010301', departmentName: '事務企画推進部' },
  { documentType: 'C010302', departmentName: '事務企画推進部' },
  { documentType: 'C010303', departmentName: '事務企画推進部' },
  { documentType: 'C010304', departmentName: '事務企画推進部' },
  { documentType: 'C010305', departmentName: '事務企画推進部' },
  { documentType: 'C010306', departmentName: '事務企画推進部' },
  { documentType: 'C010307', departmentName: '事務企画推進部' },
  { documentType: 'C010308', departmentName: '事務企画推進部' },
  { documentType: 'C010309', departmentName: '事務企画推進部' },
  { documentType: 'C010310', departmentName: '事務企画推進部' },
  { documentType: 'C010311', departmentName: '事務企画推進部' },
  { documentType: 'C010312', departmentName: '事務企画推進部' },
  { documentType: 'C010313', departmentName: '事務企画推進部' },
  { documentType: 'C010314', departmentName: '事務企画推進部' },
  { documentType: 'C010315', departmentName: '事務企画推進部' },
  { documentType: 'C010316', departmentName: '事務企画推進部' },
  { documentType: 'C010317', departmentName: '事務企画推進部' },
  { documentType: 'C010318', departmentName: '事務企画推進部' },
  { documentType: 'C010319', departmentName: '事務企画推進部' },
  { documentType: 'C010320', departmentName: '事務企画推進部' },
  { documentType: 'C010321', departmentName: '事務企画推進部' },
  { documentType: 'C010322', departmentName: '事務企画推進部' },
  { documentType: 'C020101', departmentName: 'UIUX企画推進部' },
  { documentType: 'C020102', departmentName: 'UIUX企画推進部' },
  { documentType: 'C020103', departmentName: 'UIUX企画推進部' },
  { documentType: 'C020104', departmentName: 'UIUX企画推進部' },
  { documentType: 'C020105', departmentName: '事務企画推進部' },
  { documentType: 'C030101', departmentName: '住宅ローン営業第一部' },
  { documentType: 'C030102', departmentName: '住宅ローン営業第一部' },
  { documentType: 'C030103', departmentName: '住宅ローン営業第一部' },
  { documentType: 'C030104', departmentName: '住宅ローン営業第一部' },
  { documentType: 'C040101', departmentName: '住宅ローン営業第二部' },
  { documentType: 'C040102', departmentName: '住宅ローン営業第二部' },
  { documentType: 'C040103', departmentName: '住宅ローン営業第二部' },
  { documentType: 'C040104', departmentName: '住宅ローン営業第二部' },
  { documentType: 'C050601', departmentName: 'サービス企画推進部' },
  { documentType: 'C050602', departmentName: 'サービス企画推進部' },
  { documentType: 'C050603', departmentName: 'サービス企画推進部' },
  { documentType: 'C050604', departmentName: 'サービス企画推進部' },
  { documentType: 'C050605', departmentName: 'サービス企画推進部' },
  { documentType: 'C060101', departmentName: 'マーケティング部' },
  { documentType: 'C060102', departmentName: 'マーケティング部' },
  { documentType: 'C060103', departmentName: 'マーケティング部' },
  { documentType: 'C060104', departmentName: 'マーケティング部' },
  { documentType: 'C060105', departmentName: 'マーケティング部' },
  { documentType: 'C060106', departmentName: 'マーケティング部' },
  { documentType: 'C060201', departmentName: 'マーケティング部' },
  { documentType: 'C060202', departmentName: 'マーケティング部' },
  { documentType: 'C060301', departmentName: 'マーケティング部' },
  { documentType: 'C060302', departmentName: 'マーケティング部' },
  { documentType: 'C060303', departmentName: 'マーケティング部' },
  { documentType: 'C060401', departmentName: 'マーケティング部' },
  { documentType: 'C060402', departmentName: 'マーケティング部' },
  { documentType: 'C060403', departmentName: 'マーケティング部' },
  { documentType: 'C060501', departmentName: 'マーケティング部' },
  { documentType: 'C060601', departmentName: 'マーケティング部' },
  { documentType: 'C060602', departmentName: 'マーケティング部' },
  { documentType: 'C060603', departmentName: 'マーケティング部' },
  { documentType: 'C060801', departmentName: 'マーケティング部' },
  { documentType: 'C060802', departmentName: 'マーケティング部' },
  { documentType: 'C060803', departmentName: 'マーケティング部' },
  { documentType: 'C060901', departmentName: 'マーケティング部' },
  { documentType: 'C060902', departmentName: 'マーケティング部' },
  { documentType: 'C060903', departmentName: 'マーケティング部' },
] as const;

export type DocumentType = (typeof DOCUMENT_TYPE_LIST)[number]['documentType'];
